using ArturRios.Heimdall.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ArturRios.Heimdall.Data.EntityMaps;

internal static class RoleDbMap
{
    public static void Configure(this EntityTypeBuilder<Role> role)
    {
        role.ToTable("role");

        role.HasKey(x => x.Id);

        // Role ids are assigned from the Roles enum by DatabaseSeeder (SystemAdmin = 1,
        // ScopeAdmin = 2, User = 3), not generated by the database. Roles are fixed reference data
        // (FR-RO-01), so there is no identity sequence left to drift out of step with the rows.
        role.Property(x => x.Id).ValueGeneratedNever();

        role.Property(x => x.PublicId).IsRequired();
        role.HasIndex(x => x.PublicId).IsUnique();

        role.Property(x => x.Name).IsRequired();

        // Role name is unique — User | ScopeAdmin | SystemAdmin (§4.3).
        role.HasIndex(x => x.Name).IsUnique();

        // The Person -> Role relationship is configured in PersonDbMap.
    }
}
