<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="ArturRios.Mediator" Version="1.0.1" />
      <PackageReference Include="ArturRios.Data.Relational.Core" Version="3.0.0" />
      <PackageReference Include="ArturRios.Util" Version="1.4.0" />
      <PackageReference Include="FluentValidation" Version="12.1.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Domain\ArturRios.IdentityManager.Domain\ArturRios.IdentityManager.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Input\Validation\" />
    </ItemGroup>

</Project>
